/**
 * Virtual windowing for the transcript message list.
 *
 * The transcript is append-only and can be very large (thousands of
 * messages). Rendering every message in the DOM is prohibitively slow for
 * long transcripts. This hook calculates which messages are currently
 * visible (plus an overscan buffer) so only those are rendered. Spacer
 * divs above and below stand in for unrendered messages, keeping the
 * scrollbar proportional to the full transcript length.
 *
 * Design:
 * - The visible range is [startIndex, endIndex) — a slice of the full
 *   Message[] array.
 * - An average row height is maintained by measuring the rendered content
 *   after each visible-range change. Unrendered regions use this average
 *   for spacer height estimation.
 * - On scroll, the visible range is recalculated from scrollTop /
 *   avgRowHeight, with an overscan buffer on each side. Scroll events are
 *   coalesced via requestAnimationFrame so multiple events within one
 *   frame produce a single range update.
 * - When avgRowHeight changes (after measuring newly-rendered content),
 *   scrollTop is adjusted by the spacer-height delta so the visible
 *   content doesn't jump. A synthetic-scroll flag suppresses the scroll
 *   event that the browser fires for this programmatic scrollTop change,
 *   breaking the feedback loop (scroll → range change → measure →
 *   avgRowHeight change → spacer change → scroll → ...).
 * - When new messages arrive (messageCount increases), the window sticks
 *   to the bottom if the user was already at the bottom; otherwise the
 *   range stays put.
 * - On session switch (resetKey change), the window resets to the bottom.
 */

import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react'

const OVERSCAN = 50
const ESTIMATED_ROW_HEIGHT = 120
const MIN_RENDERED = 100

export interface VirtualWindow {
  /** First message index to render (inclusive). */
  startIndex: number
  /** Last message index to render (exclusive). */
  endIndex: number
  /** Height in px for the spacer div above the rendered messages. */
  topSpacerHeight: number
  /** Height in px for the spacer div below the rendered messages. */
  bottomSpacerHeight: number
  /** Ref to attach to the div wrapping the rendered messages. Used to
   *  measure actual content height and refine the average row height. */
  contentRef: React.RefObject<HTMLDivElement>
}

export function useVirtualWindow(
  messageCount: number,
  scrollerRef: React.RefObject<HTMLDivElement>,
  /** When this value changes, the window resets to the bottom (used for
   *  session switches). */
  resetKey: string | null,
): VirtualWindow {
  // Initial state: render the bottom of the transcript.
  const [visibleRange, setVisibleRange] = useState<[number, number]>(() => {
    const start = Math.max(0, messageCount - MIN_RENDERED)
    return [start, messageCount]
  })

  // avgRowHeight is state (not a ref) so that updating it triggers a
  // re-render with corrected spacer heights. This is critical for scroll
  // position preservation: the scrollTop adjustment must happen in the
  // same synchronous layout phase as the spacer height change, which
  // requires both to be in the same render commit.
  const [avgRowHeight, setAvgRowHeight] = useState(ESTIMATED_ROW_HEIGHT)
  const contentRef = useRef<HTMLDivElement>(null)
  const wasAtBottom = useRef(true)
  // Suppresses the synthetic scroll event generated by the programmatic
  // scrollTop adjustment in the measurement effect. Without this, the
  // adjustment triggers a scroll event → updateVisibleRange → re-render →
  // measurement → adjustment → ..., an infinite feedback loop.
  const syntheticScrollRef = useRef(false)

  // Reset to bottom on session change.
  useEffect(() => {
    const start = Math.max(0, messageCount - MIN_RENDERED)
    setVisibleRange([start, messageCount])
    setAvgRowHeight(ESTIMATED_ROW_HEIGHT)
    wasAtBottom.current = true
  }, [resetKey]) // eslint-disable-line react-hooks/exhaustive-deps

  // Measure rendered content height after the visible range changes and
  // update the average row height. useLayoutEffect runs after DOM commit
  // but before paint, so the measurement and scrollTop adjustment are
  // applied before the user sees anything.
  //
  // deps: [visibleRange] — only measure when the rendered content changes,
  // not on every render. Running on every render (the previous behavior)
  // caused avgRowHeight to update even on unrelated re-renders, which
  // changed spacer heights, which shifted scrollTop, which triggered
  // another scroll event — the feedback loop that caused flicker on large
  // transcripts (22,000+ messages).
  useLayoutEffect(() => {
    const el = contentRef.current
    if (!el) return
    const renderedCount = visibleRange[1] - visibleRange[0]
    if (renderedCount <= 0) return
    const measuredHeight = el.offsetHeight
    if (measuredHeight <= 0) return
    const newAvg = measuredHeight / renderedCount
    // Conservative blending (0.85 old + 0.15 new) — a single chunk of
    // tall or short messages shouldn't drastically change the estimate.
    // The previous 0.3/0.7 blend caused oscillation: the average swung
    // wildly as different-height messages entered the viewport, each
    // swing changing spacer heights, shifting scrollTop, and triggering
    // another measurement.
    const blendedAvg = Math.round(avgRowHeight * 0.85 + newAvg * 0.15)
    if (blendedAvg === avgRowHeight) return
    // Scroll position preservation: when avgRowHeight changes, the top
    // spacer height changes by startIndex * delta. Adjust scrollTop by
    // that delta so the visible content stays in place. The synthetic-
    // scroll flag suppresses the scroll event the browser fires for this
    // programmatic adjustment, breaking the feedback loop.
    const spacerDelta = visibleRange[0] * (blendedAvg - avgRowHeight)
    setAvgRowHeight(blendedAvg)
    const scroller = scrollerRef.current
    if (scroller && Math.abs(spacerDelta) >= 1) {
      syntheticScrollRef.current = true
      scroller.scrollTop += spacerDelta
    }
  }, [visibleRange]) // eslint-disable-line react-hooks/exhaustive-deps

  // Recalculate the visible range from the current scroll position.
  const updateVisibleRange = useCallback(() => {
    const el = scrollerRef.current
    if (!el || messageCount === 0) return

    const scrollTop = el.scrollTop
    const viewportHeight = el.clientHeight
    const avg = avgRowHeight

    const firstVisible = Math.max(0, Math.floor(scrollTop / avg) - OVERSCAN)
    const lastVisible = Math.min(
      messageCount,
      Math.ceil((scrollTop + viewportHeight) / avg) + OVERSCAN,
    )

    // Ensure at least MIN_RENDERED messages are rendered.
    const rangeSize = lastVisible - firstVisible
    const ensuredEnd = Math.min(
      messageCount,
      firstVisible + Math.max(rangeSize, MIN_RENDERED),
    )

    setVisibleRange((prev) => {
      if (prev[0] === firstVisible && prev[1] === ensuredEnd) return prev
      return [firstVisible, ensuredEnd]
    })

    wasAtBottom.current =
      el.scrollHeight - el.scrollTop - el.clientHeight < 80
  }, [scrollerRef, messageCount, avgRowHeight])

  // Scroll event listener with rAF coalescing. Multiple scroll events
  // within one animation frame (common during fast scrolling or when the
  // browser generates synthetic scroll events from layout shifts) are
  // coalesced into a single updateVisibleRange call. This prevents
  // rapid-fire state updates that would cause render thrashing.
  useEffect(() => {
    const el = scrollerRef.current
    if (!el) return
    let rafId: number | null = null
    const onScroll = () => {
      // Ignore the synthetic scroll event from the scrollTop adjustment
      // in the measurement useLayoutEffect. This breaks the feedback
      // loop: measure → adjust scrollTop → scroll event → (suppressed).
      if (syntheticScrollRef.current) {
        syntheticScrollRef.current = false
        return
      }
      if (rafId !== null) return
      rafId = requestAnimationFrame(() => {
        rafId = null
        updateVisibleRange()
      })
    }
    el.addEventListener('scroll', onScroll, { passive: true })
    return () => {
      el.removeEventListener('scroll', onScroll)
      if (rafId !== null) cancelAnimationFrame(rafId)
    }
  }, [scrollerRef, updateVisibleRange])

  // When new messages arrive, stick to bottom or keep the current range.
  useEffect(() => {
    if (messageCount === 0) {
      setVisibleRange([0, 0])
      return
    }
    if (wasAtBottom.current) {
      // Extend the window to include new messages at the bottom.
      setVisibleRange((prev) => {
        const size = Math.max(prev[1] - prev[0], MIN_RENDERED)
        const start = Math.max(0, messageCount - size)
        return [start, messageCount]
      })
    }
    // If not at bottom, the existing range is still valid — the new
    // messages are below the viewport and will be rendered when the
    // user scrolls down. But the bottom spacer height changes, which
    // is handled by the spacer calculation below.
  }, [messageCount]) // eslint-disable-line react-hooks/exhaustive-deps

  const [startIndex, endIndex] = visibleRange
  const topSpacerHeight = Math.round(startIndex * avgRowHeight)
  const bottomSpacerHeight = Math.round((messageCount - endIndex) * avgRowHeight)

  return {
    startIndex,
    endIndex,
    topSpacerHeight,
    bottomSpacerHeight,
    contentRef,
  }
}